[package]
name = "pc-ps2-controller"
version = "0.1.0"
authors = ["Juuso Tuononen <jutuon@outlook.com>"]
edition = "2018"
publish = false

[dependencies]
pc-keyboard = "0.5.0"
bitflags = "1.0"
arraydeque = { version = "0.4", default-features = false }
